package com.yunyin.music.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

/**
 * Icon vectors imported from **Google Material Symbols**.
 *
 * Generated by `tools/import_material_symbols.py` from the official SVGs; do not edit by hand.
 * Kept in their own file so the generated shapes stay separable from the hand-drawn
 * [SfIcons] set, and so a regeneration produces a reviewable diff.
 *
 * Source: https://github.com/google/material-design-icons — Material Symbols, Apache-2.0.
 * The 960-unit grid they are drawn on is preserved as the vector viewport.
 */
object MaterialSymbols {

    /** One ascending bar — the lowest tier. */
    val SignalCellularAlt1Bar: ImageVector = ImageVector.Builder(
        name = "signal_cellular_alt_1_bar",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f, 
        viewportHeight = 960f,
    ).apply {
        path(
            fill = SolidColor(Color.Black),
            name = "signal_cellular_alt_1_bar.0",
            pathBuilder = {
                moveTo(200f, 800f)
                verticalLineToRelative(-240f)
                horizontalLineToRelative(120f)
                verticalLineToRelative(240f)
                horizontalLineTo(200f)
                close()
            },
        )
    }.build()

    /** Two ascending bars. */
    val SignalCellularAlt2Bar: ImageVector = ImageVector.Builder(
        name = "signal_cellular_alt_2_bar",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f, 
        viewportHeight = 960f,
    ).apply {
        path(
            fill = SolidColor(Color.Black),
            name = "signal_cellular_alt_2_bar.0",
            pathBuilder = {
                moveTo(200f, 800f)
                verticalLineToRelative(-240f)
                horizontalLineToRelative(120f)
                verticalLineToRelative(240f)
                horizontalLineTo(200f)
                close()
                moveToRelative(240f, 0f)
                verticalLineToRelative(-440f)
                horizontalLineToRelative(120f)
                verticalLineToRelative(440f)
                horizontalLineTo(440f)
                close()
            },
        )
    }.build()

    /** Three ascending bars — the highest lossy tier. */
    val SignalCellularAlt: ImageVector = ImageVector.Builder(
        name = "signal_cellular_alt",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f, 
        viewportHeight = 960f,
    ).apply {
        path(
            fill = SolidColor(Color.Black),
            name = "signal_cellular_alt.0",
            pathBuilder = {
                moveTo(200f, 800f)
                verticalLineToRelative(-240f)
                horizontalLineToRelative(120f)
                verticalLineToRelative(240f)
                horizontalLineTo(200f)
                close()
                moveToRelative(240f, 0f)
                verticalLineToRelative(-440f)
                horizontalLineToRelative(120f)
                verticalLineToRelative(440f)
                horizontalLineTo(440f)
                close()
                moveToRelative(240f, 0f)
                verticalLineToRelative(-640f)
                horizontalLineToRelative(120f)
                verticalLineToRelative(640f)
                horizontalLineTo(680f)
                close()
            },
        )
    }.build()

    /** A faceted gem, used as the lossless badge. */
    val Diamond: ImageVector = ImageVector.Builder(
        name = "diamond",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f, 
        viewportHeight = 960f,
    ).apply {
        path(
            fill = SolidColor(Color.Black),
            name = "diamond.0",
            pathBuilder = {
                moveTo(480f, 840f)
                lineTo(80f, 360f)
                lineToRelative(120f, -240f)
                horizontalLineToRelative(560f)
                lineToRelative(120f, 240f)
                lineToRelative(-400f, 480f)
                close()
                moveToRelative(-95f, -520f)
                horizontalLineToRelative(190f)
                lineToRelative(-60f, -120f)
                horizontalLineToRelative(-70f)
                lineToRelative(-60f, 120f)
                close()
                moveToRelative(55f, 347f)
                verticalLineToRelative(-267f)
                horizontalLineTo(218f)
                lineToRelative(222f, 267f)
                close()
                moveToRelative(80f, 0f)
                lineToRelative(222f, -267f)
                horizontalLineTo(520f)
                verticalLineToRelative(267f)
                close()
                moveToRelative(144f, -347f)
                horizontalLineToRelative(106f)
                lineToRelative(-60f, -120f)
                horizontalLineTo(604f)
                lineToRelative(60f, 120f)
                close()
                moveToRelative(-474f, 0f)
                horizontalLineToRelative(106f)
                lineToRelative(60f, -120f)
                horizontalLineTo(250f)
                lineToRelative(-60f, 120f)
                close()
            },
        )
    }.build()

    /** The HD badge, used as the hi-res badge. */
    val Hd: ImageVector = ImageVector.Builder(
        name = "hd",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f, 
        viewportHeight = 960f,
    ).apply {
        path(
            fill = SolidColor(Color.Black),
            name = "hd.0",
            pathBuilder = {
                moveTo(240f, 600f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(-80f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(80f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(-240f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(100f)
                horizontalLineToRelative(-80f)
                verticalLineToRelative(-100f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(240f)
                close()
                moveToRelative(280f, 0f)
                horizontalLineToRelative(160f)
                quadToRelative(17f, 0f, 28.5f, -11.5f)
                reflectiveQuadTo(720f, 560f)
                verticalLineToRelative(-160f)
                quadToRelative(0f, -17f, -11.5f, -28.5f)
                reflectiveQuadTo(680f, 360f)
                horizontalLineTo(520f)
                verticalLineToRelative(240f)
                close()
                moveToRelative(60f, -60f)
                verticalLineToRelative(-120f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(120f)
                horizontalLineToRelative(-80f)
                close()
                moveTo(160f, 800f)
                quadToRelative(-33f, 0f, -56.5f, -23.5f)
                reflectiveQuadTo(80f, 720f)
                verticalLineToRelative(-480f)
                quadToRelative(0f, -33f, 23.5f, -56.5f)
                reflectiveQuadTo(160f, 160f)
                horizontalLineToRelative(640f)
                quadToRelative(33f, 0f, 56.5f, 23.5f)
                reflectiveQuadTo(880f, 240f)
                verticalLineToRelative(480f)
                quadToRelative(0f, 33f, -23.5f, 56.5f)
                reflectiveQuadTo(800f, 800f)
                horizontalLineTo(160f)
                close()
                moveToRelative(0f, -80f)
                horizontalLineToRelative(640f)
                verticalLineToRelative(-480f)
                horizontalLineTo(160f)
                verticalLineToRelative(480f)
                close()
                moveToRelative(0f, 0f)
                verticalLineToRelative(-480f)
                verticalLineToRelative(480f)
                close()
            },
        )
    }.build()

}
